Tracker:AddLocations("locations/Bomb.json")
Tracker:AddLocations("locations/Chapter 1.json")
Tracker:AddLocations("locations/Chapter 10.json")
Tracker:AddLocations("locations/Chapter 11.json")
Tracker:AddLocations("locations/Chapter 12.json")
Tracker:AddLocations("locations/Chapter 13.json")
Tracker:AddLocations("locations/Chapter 2.json")
Tracker:AddLocations("locations/Chapter 3.json")
Tracker:AddLocations("locations/Chapter 4.json")
Tracker:AddLocations("locations/Chapter 5.json")
Tracker:AddLocations("locations/Chapter 6.json")
Tracker:AddLocations("locations/Chapter 7.json")
Tracker:AddLocations("locations/Chapter 8.json")
Tracker:AddLocations("locations/Chapter 9.json")
Tracker:AddLocations("locations/Gun.json")
Tracker:AddLocations("locations/Legs.json")
Tracker:AddLocations("locations/Pod.json")
Tracker:AddLocations("locations/Robo.json")
Tracker:AddLocations("locations/Overworld.json")
